spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 9422
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    encoding: UTF-8
    content-type: text/html; charset=UTF-8
    servlet:
      content-type: text/html; charset=UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
