spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db
    username: root
    password: 9422
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
